from sqlalchemy import select
from ...database import AsyncSessionLocal
from ...models.wines import Wine


async def seed_red():
    async with AsyncSessionLocal() as session:
        # Skip if already seeded
        result = await session.execute(select(Wine).where(Wine.color == "red").limit(1))
        if result.scalar_one_or_none():
            print("Red wines already seeded, skipping.")
            return
        red_wines = [
            Wine(
                id=582,
                producer="Château Lanessan",
                name="Cru Bourgeois",
                region="Bordeaux",
                country="France",
                appellation="Haut-Médoc",
                vintage=2020,
                grape_variety="Cabernet Sauvignon Merlot",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2032,
                market_price=18.00,
            ),
            Wine(
                id=583,
                producer="Château Beaumont",
                name="Cru Bourgeois",
                region="Bordeaux",
                country="France",
                appellation="Haut-Médoc",
                vintage=2020,
                grape_variety="Cabernet Sauvignon Merlot",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2030,
                market_price=16.00,
            ),
            Wine(
                id=584,
                producer="Château Potensac",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Médoc",
                vintage=2019,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.50,
                drink_from=2024,
                drink_to=2036,
                market_price=24.00,
            ),
            Wine(
                id=585,
                producer="Château Meyney",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Estèphe",
                vintage=2018,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.50,
                drink_from=2025,
                drink_to=2038,
                market_price=28.00,
            ),
            Wine(
                id=586,
                producer="Château Gloria",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Julien",
                vintage=2019,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.50,
                drink_from=2025,
                drink_to=2040,
                market_price=42.00,
            ),
            Wine(
                id=587,
                producer="Château Chasse-Spleen",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Moulis-en-Médoc",
                vintage=2020,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.50,
                drink_from=2024,
                drink_to=2035,
                market_price=32.00,
            ),
            Wine(
                id=588,
                producer="Château Sociando-Mallet",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Haut-Médoc",
                vintage=2018,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.50,
                drink_from=2025,
                drink_to=2040,
                market_price=36.00,
            ),
            Wine(
                id=589,
                producer="Château Cantemerle",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Haut-Médoc",
                vintage=2019,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2036,
                market_price=30.00,
            ),
            Wine(
                id=590,
                producer="Echo de Lynch-Bages",
                name="Second Vin",
                region="Bordeaux",
                country="France",
                appellation="Pauillac",
                vintage=2020,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.50,
                drink_from=2024,
                drink_to=2035,
                market_price=44.00,
            ),
            Wine(
                id=591,
                producer="Les Pagodes de Cos",
                name="Second Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Estèphe",
                vintage=2019,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.50,
                drink_from=2024,
                drink_to=2038,
                market_price=46.00,
            ),
            Wine(
                id=592,
                producer="Clos du Marquis",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Julien",
                vintage=2018,
                grape_variety="Cabernet Sauvignon Blend",
                color="red",
                alcohol=13.50,
                drink_from=2025,
                drink_to=2042,
                market_price=54.00,
            ),
            Wine(
                id=593,
                producer="Château Tour Saint Christophe",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Émilion",
                vintage=2019,
                grape_variety="Merlot Cabernet Franc",
                color="red",
                alcohol=14.00,
                drink_from=2024,
                drink_to=2038,
                market_price=34.00,
            ),
            Wine(
                id=594,
                producer="Château Fonplégade",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Émilion",
                vintage=2018,
                grape_variety="Merlot Cabernet Franc",
                color="red",
                alcohol=14.00,
                drink_from=2024,
                drink_to=2040,
                market_price=36.00,
            ),
            Wine(
                id=595,
                producer="Château de Reignac",
                name="Grand Vin de Reignac",
                region="Bordeaux",
                country="France",
                appellation="Bordeaux Supérieur",
                vintage=2019,
                grape_variety="Merlot Cabernet Sauvignon",
                color="red",
                alcohol=14.00,
                drink_from=2023,
                drink_to=2034,
                market_price=18.00,
            ),
            Wine(
                id=596,
                producer="Château La Fleur-Pétrus",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Pomerol",
                vintage=2018,
                grape_variety="Merlot Cabernet Franc",
                color="red",
                alcohol=14.00,
                drink_from=2026,
                drink_to=2045,
                market_price=58.00,
            ),
            Wine(
                id=597,
                producer="Château La Conseillante",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Pomerol",
                vintage=2017,
                grape_variety="Merlot Cabernet Franc",
                color="red",
                alcohol=14.00,
                drink_from=2025,
                drink_to=2045,
                market_price=68.00,
            ),
            Wine(
                id=598,
                producer="Château Canon",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Émilion",
                vintage=2018,
                grape_variety="Merlot Cabernet Franc",
                color="red",
                alcohol=14.00,
                drink_from=2025,
                drink_to=2048,
                market_price=58.00,
            ),
            Wine(
                id=599,
                producer="Château Figeac",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Émilion",
                vintage=2019,
                grape_variety="Cabernet Franc Merlot",
                color="red",
                alcohol=13.50,
                drink_from=2026,
                drink_to=2050,
                market_price=82.00,
            ),
            Wine(
                id=600,
                producer="Château Pavie Macquin",
                name="Grand Vin",
                region="Bordeaux",
                country="France",
                appellation="Saint-Émilion",
                vintage=2019,
                grape_variety="Merlot Cabernet Franc",
                color="red",
                alcohol=14.50,
                drink_from=2025,
                drink_to=2045,
                market_price=48.00,
            ),
            Wine(
                id=607,
                producer="Domaine Faiveley",
                name="Mercurey Vieilles Vignes",
                region="Burgundy",
                country="France",
                appellation="Mercurey",
                vintage=2021,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2032,
                market_price=28.00,
            ),
            Wine(
                id=608,
                producer="Joseph Drouhin",
                name="Savigny-lès-Beaune",
                region="Burgundy",
                country="France",
                appellation="Savigny-lès-Beaune",
                vintage=2020,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2034,
                market_price=34.00,
            ),
            Wine(
                id=609,
                producer="Louis Jadot",
                name="Beaune Premier Cru",
                region="Burgundy",
                country="France",
                appellation="Beaune",
                vintage=2020,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.50,
                drink_from=2025,
                drink_to=2038,
                market_price=48.00,
            ),
            Wine(
                id=610,
                producer="Domaine Michel Gros",
                name="Bourgogne Côte d'Or",
                region="Burgundy",
                country="France",
                appellation="Bourgogne",
                vintage=2021,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.00,
                drink_from=2023,
                drink_to=2030,
                market_price=24.00,
            ),
            Wine(
                id=611,
                producer="Domaine Pavelot",
                name="Pernand-Vergelesses",
                region="Burgundy",
                country="France",
                appellation="Pernand-Vergelesses",
                vintage=2020,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2035,
                market_price=42.00,
            ),
            Wine(
                id=612,
                producer="Domaine Arlaud",
                name="Morey-Saint-Denis",
                region="Burgundy",
                country="France",
                appellation="Morey-Saint-Denis",
                vintage=2019,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.50,
                drink_from=2025,
                drink_to=2040,
                market_price=74.00,
            ),
            Wine(
                id=613,
                producer="Domaine Trapet",
                name="Gevrey-Chambertin",
                region="Burgundy",
                country="France",
                appellation="Gevrey-Chambertin",
                vintage=2020,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.50,
                drink_from=2025,
                drink_to=2045,
                market_price=88.00,
            ),
            Wine(
                id=614,
                producer="Domaine Hubert Lignier",
                name="Monthelie",
                region="Burgundy",
                country="France",
                appellation="Monthélie",
                vintage=2021,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2033,
                market_price=36.00,
            ),
            Wine(
                id=615,
                producer="Domaine Bachelet-Monnot",
                name="Maranges Rouge",
                region="Burgundy",
                country="France",
                appellation="Maranges",
                vintage=2021,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2030,
                market_price=26.00,
            ),
            Wine(
                id=622,
                producer="E. Guigal",
                name="Côtes du Rhône Rouge",
                region="Rhône",
                country="France",
                appellation="Côtes du Rhône",
                vintage=2021,
                grape_variety="Grenache Syrah Mourvèdre",
                color="red",
                alcohol=14.00,
                drink_from=2023,
                drink_to=2029,
                market_price=12.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=623,
                producer="Famille Perrin",
                name="Réserve Rouge",
                region="Rhône",
                country="France",
                appellation="Côtes du Rhône",
                vintage=2021,
                grape_variety="Grenache Syrah Mourvèdre",
                color="red",
                alcohol=13.50,
                drink_from=2023,
                drink_to=2028,
                market_price=11.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=624,
                producer="M. Chapoutier",
                name="Belleruche Rouge",
                region="Rhône",
                country="France",
                appellation="Côtes du Rhône",
                vintage=2022,
                grape_variety="Grenache Syrah",
                color="red",
                alcohol=13.50,
                drink_from=2023,
                drink_to=2028,
                market_price=10.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=625,
                producer="Paul Jaboulet Aîné",
                name="Parallèle 45",
                region="Rhône",
                country="France",
                appellation="Côtes du Rhône",
                vintage=2021,
                grape_variety="Grenache Syrah",
                color="red",
                alcohol=13.50,
                drink_from=2023,
                drink_to=2028,
                market_price=9.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=626,
                producer="Domaine du Pegau",
                name="Cuvée Réservée",
                region="Rhône",
                country="France",
                appellation="Châteauneuf-du-Pape",
                vintage=2019,
                grape_variety="Grenache Blend",
                color="red",
                alcohol=15.00,
                drink_from=2024,
                drink_to=2040,
                market_price=46.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=627,
                producer="Clos des Papes",
                name="Châteauneuf-du-Pape",
                region="Rhône",
                country="France",
                appellation="Châteauneuf-du-Pape",
                vintage=2020,
                grape_variety="Grenache Blend",
                color="red",
                alcohol=15.00,
                drink_from=2025,
                drink_to=2045,
                market_price=82.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=628,
                producer="Jean-Louis Chave",
                name="Hermitage",
                region="Rhône",
                country="France",
                appellation="Hermitage",
                vintage=2018,
                grape_variety="Syrah",
                color="red",
                alcohol=14.00,
                drink_from=2026,
                drink_to=2050,
                market_price=140.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=629,
                producer="E. Guigal",
                name="La Mouline",
                region="Rhône",
                country="France",
                appellation="Côte-Rôtie",
                vintage=2017,
                grape_variety="Syrah Viognier",
                color="red",
                alcohol=14.00,
                drink_from=2027,
                drink_to=2055,
                market_price=220.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=630,
                producer="Yves Cuilleron",
                name="Madinière",
                region="Rhône",
                country="France",
                appellation="Saint-Joseph",
                vintage=2021,
                grape_variety="Syrah",
                color="red",
                alcohol=13.50,
                drink_from=2024,
                drink_to=2035,
                market_price=28.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=631,
                producer="François Villard",
                name="Mairlant",
                region="Rhône",
                country="France",
                appellation="Saint-Joseph",
                vintage=2021,
                grape_variety="Syrah",
                color="red",
                alcohol=13.50,
                drink_from=2024,
                drink_to=2035,
                market_price=24.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=635,
                producer="Thierry Germain",
                name="Saumur-Champigny",
                region="Loire",
                country="France",
                appellation="Saumur-Champigny",
                vintage=2020,
                grape_variety="Cabernet Franc",
                color="red",
                alcohol=13.00,
                drink_from=2023,
                drink_to=2035,
                market_price=22.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=636,
                producer="Clos Rougeard",
                name="Les Poyeux",
                region="Loire",
                country="France",
                appellation="Saumur-Champigny",
                vintage=2018,
                grape_variety="Cabernet Franc",
                color="red",
                alcohol=13.00,
                drink_from=2025,
                drink_to=2050,
                market_price=180.00,
                created_at="2026-05-18 11:39:41.341439",
            ),
            Wine(
                id=637,
                producer="Vietti",
                name="Perbacco",
                region="Piedmont",
                country="Italy",
                appellation="Langhe",
                vintage=2020,
                grape_variety="Nebbiolo",
                color="red",
                alcohol=14.00,
                drink_from=2024,
                drink_to=2038,
                market_price=32.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=638,
                producer="G.D. Vajra",
                name="Albe",
                region="Piedmont",
                country="Italy",
                appellation="Barolo",
                vintage=2019,
                grape_variety="Nebbiolo",
                color="red",
                alcohol=14.00,
                drink_from=2025,
                drink_to=2045,
                market_price=42.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=639,
                producer="Produttori del Barbaresco",
                name="Barbaresco",
                region="Piedmont",
                country="Italy",
                appellation="Barbaresco",
                vintage=2020,
                grape_variety="Nebbiolo",
                color="red",
                alcohol=14.00,
                drink_from=2025,
                drink_to=2042,
                market_price=38.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=640,
                producer="Antinori",
                name="Tignanello",
                region="Tuscany",
                country="Italy",
                appellation="Toscana IGT",
                vintage=2020,
                grape_variety="Sangiovese Cabernet Sauvignon",
                color="red",
                alcohol=14.00,
                drink_from=2025,
                drink_to=2045,
                market_price=92.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=641,
                producer="Tenuta San Guido",
                name="Le Difese",
                region="Tuscany",
                country="Italy",
                appellation="Toscana IGT",
                vintage=2021,
                grape_variety="Cabernet Sauvignon Sangiovese",
                color="red",
                alcohol=13.50,
                drink_from=2024,
                drink_to=2035,
                market_price=22.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=642,
                producer="Argiano",
                name="Brunello di Montalcino",
                region="Tuscany",
                country="Italy",
                appellation="Brunello di Montalcino",
                vintage=2018,
                grape_variety="Sangiovese",
                color="red",
                alcohol=14.00,
                drink_from=2025,
                drink_to=2045,
                market_price=48.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=643,
                producer="Zenato",
                name="Ripassa",
                region="Veneto",
                country="Italy",
                appellation="Valpolicella Ripasso",
                vintage=2020,
                grape_variety="Corvina Blend",
                color="red",
                alcohol=14.00,
                drink_from=2023,
                drink_to=2032,
                market_price=18.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=644,
                producer="Tommasi",
                name="Amarone della Valpolicella",
                region="Veneto",
                country="Italy",
                appellation="Amarone della Valpolicella",
                vintage=2018,
                grape_variety="Corvina Blend",
                color="red",
                alcohol=15.00,
                drink_from=2025,
                drink_to=2042,
                market_price=42.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=647,
                producer="La Rioja Alta",
                name="Viña Alberdi",
                region="Rioja",
                country="Spain",
                appellation="Rioja Reserva",
                vintage=2019,
                grape_variety="Tempranillo",
                color="red",
                alcohol=14.00,
                drink_from=2024,
                drink_to=2036,
                market_price=18.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=648,
                producer="CVNE",
                name="Imperial Reserva",
                region="Rioja",
                country="Spain",
                appellation="Rioja Reserva",
                vintage=2018,
                grape_variety="Tempranillo",
                color="red",
                alcohol=14.00,
                drink_from=2024,
                drink_to=2040,
                market_price=28.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=649,
                producer="López de Heredia",
                name="Viña Tondonia Reserva",
                region="Rioja",
                country="Spain",
                appellation="Rioja Reserva",
                vintage=2011,
                grape_variety="Tempranillo Blend",
                color="red",
                alcohol=13.00,
                drink_from=2024,
                drink_to=2045,
                market_price=42.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=650,
                producer="Pingus",
                name="PSI",
                region="Ribera del Duero",
                country="Spain",
                appellation="Ribera del Duero",
                vintage=2020,
                grape_variety="Tempranillo",
                color="red",
                alcohol=14.50,
                drink_from=2024,
                drink_to=2040,
                market_price=46.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=651,
                producer="Alvaro Palacios",
                name="Camins del Priorat",
                region="Priorat",
                country="Spain",
                appellation="Priorat",
                vintage=2021,
                grape_variety="Grenache Blend",
                color="red",
                alcohol=14.50,
                drink_from=2023,
                drink_to=2035,
                market_price=22.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=657,
                producer="Catena Zapata",
                name="Malbec",
                region="Mendoza",
                country="Argentina",
                appellation="Mendoza",
                vintage=2021,
                grape_variety="Malbec",
                color="red",
                alcohol=14.00,
                drink_from=2023,
                drink_to=2034,
                market_price=18.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=658,
                producer="Achaval Ferrer",
                name="Quimera",
                region="Mendoza",
                country="Argentina",
                appellation="Mendoza",
                vintage=2020,
                grape_variety="Malbec Blend",
                color="red",
                alcohol=14.50,
                drink_from=2024,
                drink_to=2038,
                market_price=32.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=660,
                producer="Felton Road",
                name="Bannockburn Pinot Noir",
                region="Central Otago",
                country="New Zealand",
                appellation="Central Otago",
                vintage=2021,
                grape_variety="Pinot Noir",
                color="red",
                alcohol=13.50,
                drink_from=2024,
                drink_to=2038,
                market_price=46.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=661,
                producer="Penfolds",
                name="Bin 28 Kalimna",
                region="South Australia",
                country="Australia",
                appellation="Barossa Valley",
                vintage=2020,
                grape_variety="Shiraz",
                color="red",
                alcohol=14.50,
                drink_from=2024,
                drink_to=2040,
                market_price=34.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=662,
                producer="Henschke",
                name="Keyneton Euphonium",
                region="South Australia",
                country="Australia",
                appellation="Barossa Valley",
                vintage=2019,
                grape_variety="Shiraz Blend",
                color="red",
                alcohol=14.50,
                drink_from=2025,
                drink_to=2045,
                market_price=58.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=664,
                producer="Ridge",
                name="Three Valleys",
                region="California",
                country="USA",
                appellation="Sonoma County",
                vintage=2020,
                grape_variety="Zinfandel Blend",
                color="red",
                alcohol=14.50,
                drink_from=2024,
                drink_to=2038,
                market_price=38.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
            Wine(
                id=666,
                producer="Duckhorn",
                name="Merlot",
                region="California",
                country="USA",
                appellation="Napa Valley",
                vintage=2020,
                grape_variety="Merlot",
                color="red",
                alcohol=14.50,
                drink_from=2024,
                drink_to=2038,
                market_price=42.00,
                created_at="2026-05-18 11:40:09.68111",
            ),
        ]
        session.add_all(red_wines)
        await session.commit()
        print(f"Seeded {len(red_wines)} wines.")
