from sqlalchemy import select
from ...database import AsyncSessionLocal
from ...models.wines import Wine

async def seed_white():
     async with AsyncSessionLocal() as session:
         # Skip if already seeded
         result = await session.execute(select(Wine).where(Wine.color == "white").limit(1))
         if result.scalar_one_or_none():
             print("White wines already seeded, skipping.")
             return
         white_wines = [
             Wine(
                 id=601,
                 producer="Château Carbonnieux",
                 name="Blanc",
                 region="Bordeaux",
                 country="France",
                 appellation="Pessac-Léognan",
                 vintage=2021,
                 grape_variety="Sauvignon Blanc Sémillon",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2030,
                 market_price=24.00,
             ),
             Wine(
                 id=602,
                 producer="Clos Floridène",
                 name="Blanc",
                 region="Bordeaux",
                 country="France",
                 appellation="Graves",
                 vintage=2021,
                 grape_variety="Sauvignon Blanc Sémillon",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2029,
                 market_price=22.00,
             ),
             Wine(
                 id=603,
                 producer="Château Rahoul",
                 name="Blanc",
                 region="Bordeaux",
                 country="France",
                 appellation="Graves",
                 vintage=2021,
                 grape_variety="Sauvignon Blanc Sémillon",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2028,
                 market_price=18.00,
             ),
             Wine(
                 id=604,
                 producer="Clos des Lunes",
                 name="Lune Blanche",
                 region="Bordeaux",
                 country="France",
                 appellation="Bordeaux Blanc",
                 vintage=2022,
                 grape_variety="Sémillon Sauvignon Blanc",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2028,
                 market_price=19.00,
             ),
             Wine(
                 id=605,
                 producer="Château Thieuley",
                 name="Blanc",
                 region="Bordeaux",
                 country="France",
                 appellation="Bordeaux Blanc",
                 vintage=2022,
                 grape_variety="Sauvignon Blanc Sémillon",
                 color="white",
                 alcohol=12.50,
                 drink_from=2023,
                 drink_to=2027,
                 market_price=14.00,
             ),
             Wine(
                 id=606,
                 producer="Domaine de Chevalier",
                 name="Blanc",
                 region="Bordeaux",
                 country="France",
                 appellation="Pessac-Léognan",
                 vintage=2020,
                 grape_variety="Sauvignon Blanc Sémillon",
                 color="white",
                 alcohol=13.50,
                 drink_from=2024,
                 drink_to=2038,
                 market_price=72.00,
             ),
             Wine(
                 id=616,
                 producer="Domaine de Villaine",
                 name="Bouzeron",
                 region="Burgundy",
                 country="France",
                 appellation="Bouzeron",
                 vintage=2022,
                 grape_variety="Aligoté",
                 color="white",
                 alcohol=12.50,
                 drink_from=2023,
                 drink_to=2028,
                 market_price=18.00,
             ),
             Wine(
                 id=617,
                 producer="Domaine Laroche",
                 name="Chablis Saint-Martin",
                 region="Burgundy",
                 country="France",
                 appellation="Chablis",
                 vintage=2022,
                 grape_variety="Chardonnay",
                 color="white",
                 alcohol=12.50,
                 drink_from=2023,
                 drink_to=2030,
                 market_price=20.00,
             ),
             Wine(
                 id=618,
                 producer="William Fèvre",
                 name="Chablis",
                 region="Burgundy",
                 country="France",
                 appellation="Chablis",
                 vintage=2021,
                 grape_variety="Chardonnay",
                 color="white",
                 alcohol=12.50,
                 drink_from=2023,
                 drink_to=2032,
                 market_price=26.00,
             ),
             Wine(
                 id=619,
                 producer="Domaine Vocoret",
                 name="Chablis Premier Cru",
                 region="Burgundy",
                 country="France",
                 appellation="Chablis Premier Cru",
                 vintage=2021,
                 grape_variety="Chardonnay",
                 color="white",
                 alcohol=13.00,
                 drink_from=2024,
                 drink_to=2035,
                 market_price=38.00,
             ),
             Wine(
                 id=620,
                 producer="Domaine Leflaive",
                 name="Mâcon-Verzé",
                 region="Burgundy",
                 country="France",
                 appellation="Mâcon-Verzé",
                 vintage=2021,
                 grape_variety="Chardonnay",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2030,
                 market_price=32.00,
             ),
             Wine(
                 id=621,
                 producer="Domaine Jacques Carillon",
                 name="Puligny-Montrachet",
                 region="Burgundy",
                 country="France",
                 appellation="Puligny-Montrachet",
                 vintage=2020,
                 grape_variety="Chardonnay",
                 color="white",
                 alcohol=13.50,
                 drink_from=2025,
                 drink_to=2040,
                 market_price=96.00,
             ),
             Wine(
                 id=632,
                 producer="Domaine Vacheron",
                 name="Sancerre Blanc",
                 region="Loire",
                 country="France",
                 appellation="Sancerre",
                 vintage=2022,
                 grape_variety="Sauvignon Blanc",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2030,
                 market_price=24.00,
                 
                 created_at="2026-05-18 11:39:41.341439",
             ),
             Wine(
                 id=633,
                 producer="Alphonse Mellot",
                 name="La Moussière",
                 region="Loire",
                 country="France",
                 appellation="Sancerre",
                 vintage=2021,
                 grape_variety="Sauvignon Blanc",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2032,
                 market_price=32.00,
                 
                 created_at="2026-05-18 11:39:41.341439",
             ),
             Wine(
                 id=634,
                 producer="Domaine Huet",
                 name="Le Haut-Lieu Demi-Sec",
                 region="Loire",
                 country="France",
                 appellation="Vouvray",
                 vintage=2021,
                 grape_variety="Chenin Blanc",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2040,
                 market_price=26.00,
                 
                 created_at="2026-05-18 11:39:41.341439",
             ),
             Wine(
                 id=645,
                 producer="Jermann",
                 name="Vintage Tunina",
                 region="Friuli",
                 country="Italy",
                 appellation="Venezia Giulia IGT",
                 vintage=2021,
                 grape_variety="Blend",
                 color="white",
                 alcohol=13.50,
                 drink_from=2023,
                 drink_to=2032,
                 market_price=44.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=646,
                 producer="Alois Lageder",
                 name="Pinot Grigio",
                 region="Alto Adige",
                 country="Italy",
                 appellation="Alto Adige",
                 vintage=2022,
                 grape_variety="Pinot Grigio",
                 color="white",
                 alcohol=12.50,
                 drink_from=2023,
                 drink_to=2027,
                 market_price=12.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=652,
                 producer="Dr. Loosen",
                 name="Blue Slate Kabinett",
                 region="Mosel",
                 country="Germany",
                 appellation="Mosel",
                 vintage=2022,
                 grape_variety="Riesling",
                 color="white",
                 alcohol=8.50,
                 drink_from=2023,
                 drink_to=2035,
                 market_price=14.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=653,
                 producer="Dönnhoff",
                 name="Tonschiefer Riesling",
                 region="Nahe",
                 country="Germany",
                 appellation="Nahe",
                 vintage=2022,
                 grape_variety="Riesling",
                 color="white",
                 alcohol=12.00,
                 drink_from=2023,
                 drink_to=2036,
                 market_price=18.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=654,
                 producer="FX Pichler",
                 name="Loibner Federspiel",
                 region="Wachau",
                 country="Austria",
                 appellation="Wachau",
                 vintage=2022,
                 grape_variety="Grüner Veltliner",
                 color="white",
                 alcohol=12.50,
                 drink_from=2023,
                 drink_to=2030,
                 market_price=22.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=655,
                 producer="Bründlmayer",
                 name="Kamptal Terrassen",
                 region="Kamptal",
                 country="Austria",
                 appellation="Kamptal",
                 vintage=2022,
                 grape_variety="Riesling",
                 color="white",
                 alcohol=12.50,
                 drink_from=2023,
                 drink_to=2032,
                 market_price=20.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=656,
                 producer="Nikolaihof",
                 name="Steiner Hund",
                 region="Wachau",
                 country="Austria",
                 appellation="Wachau",
                 vintage=2021,
                 grape_variety="Riesling",
                 color="white",
                 alcohol=12.50,
                 drink_from=2024,
                 drink_to=2040,
                 market_price=38.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=659,
                 producer="Cloudy Bay",
                 name="Sauvignon Blanc",
                 region="Marlborough",
                 country="New Zealand",
                 appellation="Marlborough",
                 vintage=2023,
                 grape_variety="Sauvignon Blanc",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2028,
                 market_price=18.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=663,
                 producer="Kumeu River",
                 name="Estate Chardonnay",
                 region="Auckland",
                 country="New Zealand",
                 appellation="Kumeu",
                 vintage=2022,
                 grape_variety="Chardonnay",
                 color="white",
                 alcohol=13.00,
                 drink_from=2023,
                 drink_to=2032,
                 market_price=24.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             ),
             Wine(
                 id=665,
                 producer="Au Bon Climat",
                 name="Santa Barbara Chardonnay",
                 region="California",
                 country="USA",
                 appellation="Santa Barbara County",
                 vintage=2021,
                 grape_variety="Chardonnay",
                 color="white",
                 alcohol=13.50,
                 drink_from=2023,
                 drink_to=2030,
                 market_price=26.00,
                 
                 created_at="2026-05-18 11:40:09.68111",
             )
         ]
         session.add_all(white_wines)
         await session.commit()
         print(f"Seeded {len(white_wines)} wines.")